# Generated by Django 3.0 on 2021-04-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_teacher_is_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mobile_number',
            new_name='father_mobile_number',
        ),
    ]
