# Generated by Django 3.0 on 2021-04-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_auto_20210404_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
